// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  if (a) {
    return add(a - 1 | 0, b) + 1 | 0;
  } else {
    return b;
  }
}

function mult(a, b) {
  if (a) {
    var n = a - 1 | 0;
    return add(mult(n, b), b);
  } else {
    return 0;
  }
}

function sub(a, b) {
  if (a) {
    var n = a - 1 | 0;
    if (b) {
      return sub(n, b - 1 | 0);
    } else {
      return a;
    }
  } else {
    return 0;
  }
}

function equal(a, b) {
  if (a) {
    var n = a - 1 | 0;
    if (b) {
      return equal(n, b - 1 | 0);
    } else {
      return /* False */1;
    }
  } else {
    if (b) {
      return /* False */1;
    } else {
      return /* True */0;
    }
  }
}

function div(a, b) {
  var _div = function (x, y, i, j) {
    if (x) {
      var n = x - 1 | 0;
      if (y) {
        var match = equal(j, y);
        if (match !== 0) {
          return _div(n, b, i, j + 1 | 0);
        } else {
          return _div(n, b, i + 1 | 0, 1);
        }
      } else {
        return x;
      }
    } else {
      return i;
    }
  };
  return _div(a, b, 0, 1);
}

exports.add   = add;
exports.mult  = mult;
exports.sub   = sub;
exports.equal = equal;
exports.div   = div;
/* No side effect */
